name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
 aeolus-bot:
   runs-on: ubuntu-latest
   if: contains(github.event.comment.body, '@aeolus')  
   steps:
    - env:
      BODY: ${{ github.event.comment.body }}
    - name: parse
      run: |
      if [[ $(echo $BODY | awk '{print $1}') == "@aeolus" ]]; then
          if [[ $(echo $BODY | awk '{print $2}') == 'please' ]]; then
              command=$(echo $BODY | awk '{for (i=3; i<NF; i++) printf $i " "; print $NF}')
              echo "Thank you for being polite.  I can certainly \"$command\"" 
          else
              echo "Please use the magic word."
          fi
      fi
