name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
 aeolus-bot:
   runs-on: ubuntu-latest
   steps:
    - name: parse
      if: contains(github.event.comment.body, '@aeolus')   
      run: |
       echo ${{ github.event.comment.body }}
