name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
 aeolus-bot:
   runs-on: ubuntu-latest
   if: contains(github.event.comment.body, '@aeolus')  
   steps:
    - env:
      BODY: ${{ github.event.comment.body }}
    - name: parse
      run: bash parse-command.sh
