name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]
jobs:
 aeolus-bot:
   if: contains(github.event.comment.body, '@aeolus')
   runs-on: [re-centos7]
   steps:
    - name: parse
      run: |
       echo ${{ github.event.comment.body }}
